Agrego ejercicio de filmina NPM
agustinpitaro/CFL-fullstack-2020 pull request #4
Opened 2020-07-17 01:48 UTC by agustinpitaro

2020-07-17 14:39 UTC, rbeltracchi approved these changes

2020-07-17 14:41 UTC, rbeltracchi requested changes

2020-07-17 14:41 UTC, rbeltracchi commented on POO/ClaseNPM-ej1/time.js
> +console.log("The time is "+time(hour, minutes));
Hiciste derecho el js? No veo el archivo TS

2020-07-17 22:41 UTC, agustinpitaro commented on POO/ClaseNPM-ej1/time.js
> +console.log("The time is "+time(hour, minutes));
Sisi, porque es el ejercicio de la filmina de NPM. Cuando resuelva la próxima filmina, lo incluyo

2020-07-18 13:14 UTC, mauri52 approved these changes

2020-08-04 00:04 UTC, merged