Agrego clases 24,26,27
agustinpitaro/CFL-fullstack-2020 pull request #5
Opened 2020-08-31 18:33 UTC by agustinpitaro

2020-09-02 15:27 UTC, rbeltracchi requested changes

2020-09-02 15:27 UTC, rbeltracchi commented on POO/Clase 24 - Herencia/telefono.ts
> +            this.estaPrendido = false;
Toda esta funcion la podrias simplificar con una sola linea haciendo `this.estaPrendido = !this.estaPrendido` pero esta bien como lo hiciste, es solo una recomendacion para que quede mejor :)

2020-09-02 15:27 UTC, rbeltracchi commented on POO/Clase 26 - Polimorfismo/estudiante.ts
> +export {Estudiante};
en vez de poner directo el export aca se lo podes poner antes del class

2020-09-02 15:27 UTC, rbeltracchi commented on POO/Clase 26 - Polimorfismo/profesor.ts
> +import {Persona} from 'C:/Users/Agustin Pitaro/Documents/CFL fullstack-2020/CFL-fullstack-2020/POO/Clase 26 - Polimorfismo/persona';
el path entero no deberia ser necesario, con usar un path relativo ya tendria que ser suficiente para encontrar la clase

2020-09-02 15:27 UTC, rbeltracchi commented on POO/Clase 27 - Interfaz + abstract/absAuto.ts
> +    abstract frenar();
es un void? O que retorna?

2020-09-02 15:27 UTC, rbeltracchi approved these changes

2020-09-04 16:36 UTC, agustinpitaro commented on POO/Clase 27 - Interfaz + abstract/absAuto.ts
> +    abstract frenar();
Era un void pero no tenia claro como era la sintaxis de Typescript aun jaja

2020-09-04 16:36 UTC, merged